### ISSUE TITLE
CSRF対策

### ISSUE THREAD

**Issue by Shitomo** [morning-night-dream/platform#63]

**Comment by Shitomo** [comment]
CSRF対策は不要([参考](https://qiita.com/mejileben/items/ae7b346f0fc4a59101b5))

Cookieは発行元へのリクエスト時に、ブラウザが勝手に返送するもの。
そのためブラウザが発行元のCookieを持っていれば、どのサイトからでも送信が可能⇒CSRF可能。

一方このプロジェクトでは、クライアント側でAuthorizationヘッダーにセットして送信するという想定。
そのため、他サイトから送信されることはない。(JWT自体が盗まれた場合は除く)

**Comment by takokun778** [comment]
上記理由により不要となったため close
